server:
  port: 8084

# Configuration Spring Boot

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/userdb   # URL de connexion à la base PostgreSQL
    username: postgres                             # Nom d'utilisateur PostgreSQL
    password: passer                               # Mot de passe PostgreSQL
    driver-class-name: org.postgresql.Driver       # Driver JDBC pour PostgreSQL

  jpa:
    hibernate:
      ddl-auto: update  # Mise à jour automatique du schéma selon les entités JPA (utile en dev)
    show-sql: true          # Affiche les requêtes SQL dans la console (debug SQL)

# Configuration Eureka Client

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka   # URL du serveur Eureka pour s’enregistrer comme client

# Configuration Swagger (OpenAPI)

springdoc:
  swagger-ui:
    path: /swagger-ui.html    # Point d’accès à l’interface Swagger UI (pour tester l’API REST)
  api-docs:
    path: /v3/api-docs    # Endpoint pour récupérer la documentation OpenAPI en JSON
